#!/usr/bin/env perl

#
# Reads in a CSV of users by day (generated by Splunk)
# and generates summaries including a histogram of # of days
# using kbase.
#
# TODO: Dump in JSON format

my $nBuckets=5;


open(E,"kbase-staff.lst") or die "Unable to open KBase Staff list";
while(<E>){
  chomp;
  $staff{$_}=1;
}
close E;

$_=<STDIN>;
chomp;
@users=split /,/;
shift @users;

while(<STDIN>){
  chomp;
  @list=split /,/;
  $time=shift @list;
  $time=~s/T.*//;
  $time=~s/"//;
  $i=0;
  foreach (@list){
    $user=$users[$i];
    $i++;
    next if $user eq '"-"';
    next if $user eq 'NULL';
    next if $_ == 0;
    $visits{$user}++;
    #print "$user $_\n";
  }
}

print "User,Visits,Staff\n";
foreach my $t (sort {$visits{$a}<=>$visits{$b}} keys %visits){
  next if $visits{$t} < 2;
  $s='';
  $s='Y' if defined $staff{$t};
  printf "%s,%4d,%s\n",$t,$visits{$t},$s;
  $totUsers++;
}

my $cs=1;
foreach my $t (sort keys %visits){
  next if $visits{$t} < 2;
  my $bucket=int($visits{$t}/$cs);
  $count[$bucket]++;
  $external[$bucket]++ if ! defined $staff{$t};
  print STDERR "Staff - $t\n" if defined $staff{$t};
}

print "Visits,Total,Non-KBase\n";
foreach my $t (0..365){
  next if $count[$t]==0;
  printf "\"%3d days\",%4d,%4d\n",$t*$cs,$count[$t],$external[$t];
}

print "\nVisits,Total,Non-KBase\n";
my $end;
foreach my $t (2..365){
  $start="$t" if $start eq '';
  next if $count[$t] == 0;
  $tot+=$count[$t];
  $ext+=$external[$t];
  $end=$t;
  if ($tot>($totUsers/$nBuckets)){
    $label="$start to $end visits";
    $label="$end visits" if $start eq $end;
    printf "\"%s\",%5d,%5d\n",$label,$tot,$ext;
    $tot=0;
    $ext=0;
    $start='';
  }
}
$label="$start to $end visits";
printf "\"%s\",%5d,%5d\n",$label,$tot,$ext;
