#!/usr/bin/env perl

#
# Reads in a CSV of users by day (generated by Splunk)
# and generates summaries including a histogram of # of days
# using kbase.
#

use JSON;

my $json = JSON->new->allow_nonref;

my $nBuckets=5;

# Read in the Staff list
#
open(E,"kbase-staff.lst") or die "Unable to open KBase Staff list";
while(<E>){
  chomp;
  $staff{$_}=1;
  $users->{$_}->{'staff'}='Y';
}
close E;

# Get all the users from the log and skip over some bogus splunk columns
#
$_=<STDIN>;
chomp;
@userl=split /,/;
shift @userl;
for my $u (@userl){
  next if defined $staff{$_};
  next if $u eq '"-"';
  next if $u eq 'NULL';
  next if $u =~ '_span';
  next if $u =~ '_spandays';
  $users->{$u}->{'staff'}='N';
}

my $start_date=0;
my $end_date=0;

# Go through each day and tally up visits
#
while(<STDIN>){
  chomp;
  @list=split /,/;
  $time=shift @list;
  $time=~s/T.*//;
  $time=~s/"//;
  $i=0;
  $start_date=$time unless $start_date ne 0;
  foreach (@list){
    $user=$userl[$i];
    $i++;
    # Skip if the user isn't in our good list
    #
    next unless defined $users->{$user};
    next if $_ == 0;
    $users->{$user}->{visits}++;
    $users->{$user}->{first}=$time if ! defined $users->{$user}->{first};
    $users->{$user}->{last}=$time;
    $visits{$user}++;
  }
}
$end_date=$time;

# Figure out how many users there are and the max visits
#
foreach my $u (sort {$visits{$a}<=>$visits{$b}} keys %visits){
  next if $visits{$u} < 2;
  $totUsers++;
  $max=$visits{$u} if $visits{$u}>$max;
}

my $counts;
foreach my $t (sort keys %visits){
  next if $visits{$t} < 2;
  my $bucket=int($visits{$t});
  $counts->{'all'}->{$bucket}++;
  $counts->{'nonkbase'}->{$bucket}++ if ! defined $staff{$t};
}

my $end;
my $b=0;
my $histo;
#$histo->{'buckets'}=$nBuckets;
$end=365;
foreach my $t (2..$max){
  $start="$t" if $start eq '';
  my $ct=$counts->{'all'}->{$t};
  my $ex=$counts->{'nonkbase'}->{$t};
  next unless defined $ct;
  $tot+=$ct;
  $ext+=$ex;
  $end=$t;
  if ($tot>($totUsers/$nBuckets) || $t eq $max){
    $label="$start to $end visits";
    $label="$end visits" if $start eq $end;
    $histo->[$b]->{label}=$label;
    $histo->[$b]->{range}->{start}=$start;
    $histo->[$b]->{range}->{end}=$end;
    $histo->[$b]->{counts}->{all}=$tot;
    $histo->[$b]->{counts}->{nonkbase}=$ext;
    $tot=0;
    $ext=0;
    $start='';
    $b++;
  }
}

my $jo;
$jo->{by_user}=$users;
$jo->{counts_by_visits}=$counts;
$jo->{histogram}=$histo;
$jo->{range}->{start}=$start_date;
$jo->{range}->{end}=$end_date;
print $json->encode($jo);

