#!/bin/sh
#
# This should be copied to /etc/cron.daily and modified
#

URL="/narrative/ws"
LDIR=/var/log/nginx
SCRIPT=/root/narrative_access.pl
OUT=/kb/deployment/access_log/access.json

(grep "GET $URL" $LDIR/access.log;zgrep --no-filename "GET $URL" $LDIR/access.log*gz)| \
   $SCRIPT | \
   python -mjson.tool> $OUT
